# Manipulating Data with NumPy

 Introduction to NumPy

In [5]:
lst = [10, 200, 90, 0]

import numpy as np
arr = np.array(lst)

print(arr + 10)

[ 20 210 100  10]


In [2]:
lst = [22, 45, 78, 50]

import numpy as np
import sys
arr = np.array(lst)
print(arr.nbytes)
print(sys.getsizeof(lst))

16
88


# NumPy Object Creation
Array Creation

In [3]:
import numpy as np
a = np.array([1,2,3,4])               # creates a 1-dimensional array
b = np.array([[1,2,3,4], [5,6,7,8]])    # creates a 2-dimensional array
print(a)
print('----')
print(b)

[1 2 3 4]
----
[[1 2 3 4]
 [5 6 7 8]]


# Useful Functions

In [4]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4,],[5,6,7,8]])

print('The shape of the array a is ', a.shape)
print('The shape of the array b is', b.shape)

The shape of the array a is  (4,)
The shape of the array b is (2, 4)


In [5]:
print('The dimensions of array a is', a.ndim)
print('Thae dimensions of array b is', b.ndim)

The dimensions of array a is 1
Thae dimensions of array b is 2


In [6]:
print('The size of the array a is', a.size)
print('The size of the array b is', b.size)

The size of the array a is 4
The size of the array b is 8


In [7]:
print('The datatype of the array a is', a.dtype)
print('The datatype of the array b is',b.dtype)

The datatype of the array a is int32
The datatype of the array b is int32


In [9]:
print('The number of bytes in each elemnt of the array a is ', a.itemsize)
print('The number of bytes in each elemnt of the array b is', b.itemsize)

The number of bytes in each elemnt of the array a is  4
The number of bytes in each elemnt of the array b is 4


#  Matrix Creation

In [10]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


In [11]:
print(np.matrix([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print( np.zeros( (4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
print(np.ones( (3,3), dtype = np.float64))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print(np.arange(1,20,dtype = 'int32'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
print(np.arange(1,20,2,dtype='int8'))

[ 1  3  5  7  9 11 13 15 17 19]


# (Practice Exercise)


In [6]:
import numpy.random as r
import numpy as np

Marks = np.array([20, 30, 40])
IDs = np.array([0,2,4])  
print(Marks,IDs)

 



[20 30 40] [0 2 4]


In [7]:
arr1 = np.array([25,56,12,85,34,75])
arr2 = np.array([42,3,86,856,46])

Narr = np.random.rand(arr1.shape[0])
print(Narr)
 

[0.3257328  0.52335863 0.88753241 0.03744571 0.91310975 0.31432486]


In [14]:
arr1= arr1.astype(complex)
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


# Indexing and Slicing

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[2][1])
print('=====')
print(a[:2,:2])
print('====')
print(a[2,:])

8
=====
[[1 2]
 [4 5]]
====
[7 8 9]


# Integer Array Indexing

In [5]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print('====')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('====')

print(a[[0,0],[1,1]])
print('====')

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
====
[1 4 5]
====
[2 2]
====
[2 2]


# Boolean Indexing

In [6]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])
mask = a > 3
print(mask)

print(a[mask])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


# Practice Exercise
Create an array with values 3, 4.5, 3 + 5j and 0. Check the values are real or imaginary

In [15]:
# practice Exersise 
import numpy as np

array = np.array([3, 4.5, 3 + 5j, 0])
print (array)
print (np.isreal(array))
print(np.iscomplex(array))


[3. +0.j 4.5+0.j 3. +5.j 0. +0.j]
[ True  True False  True]
[False False  True False]


# Vectorization

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr[arr > 2])

[3 4 5 6 7]


Vectorized Operations

In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [17]:
print(a + b)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [18]:
print(a-b)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [19]:
print(a*b)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [20]:
print (a/b)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [23]:
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]]



Practice usage of following aggregate functions

In [8]:
coefficients =  np.array([1,-4,4])
roots = np.roots(coefficients)
print(roots)

[2. 2.]


In [24]:
a = np.array([5,6,7,8])
b = np.array([5,6,7,8])
print(np.array_equal(a,b))

True


# Axes Notation

In [25]:
a = np.array ([[2,5,7],[4,25,30]])
print(a.sum(axis=0))
print('====')
print(a.sum(axis=1))
print('====')
print(a.sum())

[ 6 30 37]
====
[14 59]
====
73


# Practice Exercise

In [22]:
# practice Exersise
import numpy as np 

arr = np.array([[40, 35, 20], [21, 48, 70]])

min_price = arr.min(axis=1)[0]
print('min price of day 1:' , min_price)
print('===')
max_price = arr.max(axis=1) [1]
print('max price of day 2:', max_price)


print('===')
profit = max_price - min_price 
print('profit is:', profit)

print('===')

buy_index = np.where(arr==min_price)
sell_index = np.where(arr==max_price)

print("Index at buy : ",buy_index,"\n","Index at sell : ",sell_index)


min price of day 1: 20
===
max price of day 2: 70
===
profit is: 50
===
Index at buy :  (array([0], dtype=int64), array([2], dtype=int64)) 
 Index at sell :  (array([1], dtype=int64), array([2], dtype=int64))


# Practice Exercise

In [20]:
#practice Exersise
import numpy as np

x = np.random.random((5,5))

print(x)
print('======')
z_normmin, z_normmax = z_norm.min(), z_norm.max()
print(z_normmin,z_normmax)


[[0.60702361 0.2118448  0.30721798 0.34636691 0.34268354]
 [0.52105312 0.34161791 0.71172981 0.57255952 0.66591283]
 [0.66871122 0.96237876 0.38046925 0.51359828 0.52971118]
 [0.09004406 0.09436666 0.06005161 0.12621558 0.80178743]
 [0.58088803 0.32357656 0.41037918 0.08453715 0.29826747]]
0.010273306287195472 0.9819108137798112
