# Mini Project

In [40]:
import numpy as np

Read the Data!

In [41]:
data_file ='makeSenseOfCensus.csv'

Loading the data

In [42]:

data = np.genfromtxt(data_file, delimiter=",", skip_header=1)



print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


Printing the type of data

In [43]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


# Append the Data

In [44]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

 Check if it's a young country or old country

In [45]:
import numpy as np
census = np.genfromtxt(data_file, delimiter=",", skip_header=1)

In [46]:
age = census[:,0]

In [47]:
max_age = np.max(age)
min_age = np.min(age)
age_mean = np.mean(age)
age_std = np.std(age)

In [48]:
census[:,2]==4

array([ True,  True,  True, False, False,  True, False,  True,  True,
        True, False, False,  True, False, False, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,

In [49]:
import numpy as np
census = np.genfromtxt(data_file, delimiter=",", skip_header=1)

check the country's race distribution to identify the minorities¶

In [50]:
race = census[:,0]

In [51]:
race_4 = census[census[:,2]==4, :]

In [52]:
minority_race_number = np.min(race)

In [53]:
minority_race = list(race).index(minority_race_number)

In [54]:
senior_citizens = data[age>60]
working_hours_sum = sum(senior_citizens[:,6])
senior_citizens_len = senior_citizens.shape[0]
avg_working_hours = working_hours_sum/senior_citizens_len

print("AVERAGE WORKING HOURS : ", avg_working_hours)
if avg_working_hours>25:
    
    print("Govt. regulations not being followed")
    
elif avg_working_hours<=25:
    print("Govt. regulations are being followed")


AVERAGE WORKING HOURS :  31.42622950819672
Govt. regulations not being followed


# check that higher educated people have better pay in general

In [55]:
high = census[census[:,1]>10]

low = census[census[:,1]<=10]

avg_pay_high = np.mean(high[:,7])
avg_pay_low = np.mean(low[:,7])

print("AVERAGE PAY OF HIGHLY EDUCATED : ", avg_pay_high ,"\nAVERAGE PAY WITH LOW EDUCATION : ", avg_pay_low)
  


AVERAGE PAY OF HIGHLY EDUCATED :  0.42813455657492355 
AVERAGE PAY WITH LOW EDUCATION :  0.13670133729569092


In [56]:
avg_pay_high = np.mean(high[:,7])
avg_pay_low = np.mean(low[:,7])
avg_pay_high > avg_pay_low



True